name: facebook_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.0
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.2
  jiffy: ^6.2.1
  story_view: ^0.15.0
  uuid: ^3.0.7
  video_player: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
