// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAj_2vexMi1CVJLC1Kd1FuZZqjG8y-P88',
    appId: '1:1033950472553:web:d4badc53a2b555ad2735f8',
    messagingSenderId: '1033950472553',
    projectId: 'facebook-clone-51212',
    authDomain: 'facebook-clone-51212.firebaseapp.com',
    storageBucket: 'facebook-clone-51212.firebasestorage.app',
    measurementId: 'G-14F6YB8DTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-I4cs3G6xP4PcSW83SGa4Vfse9vwHvxU',
    appId: '1:1033950472553:android:4b7676c4f4e19ad52735f8',
    messagingSenderId: '1033950472553',
    projectId: 'facebook-clone-51212',
    storageBucket: 'facebook-clone-51212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkKFIhI1KPp563OufEsAsuHsh6EHbJqk',
    appId: '1:1033950472553:ios:cba2240032bd26ba2735f8',
    messagingSenderId: '1033950472553',
    projectId: 'facebook-clone-51212',
    storageBucket: 'facebook-clone-51212.firebasestorage.app',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjkKFIhI1KPp563OufEsAsuHsh6EHbJqk',
    appId: '1:1033950472553:ios:cba2240032bd26ba2735f8',
    messagingSenderId: '1033950472553',
    projectId: 'facebook-clone-51212',
    storageBucket: 'facebook-clone-51212.firebasestorage.app',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAj_2vexMi1CVJLC1Kd1FuZZqjG8y-P88',
    appId: '1:1033950472553:web:4dc52db4ffc020e22735f8',
    messagingSenderId: '1033950472553',
    projectId: 'facebook-clone-51212',
    authDomain: 'facebook-clone-51212.firebaseapp.com',
    storageBucket: 'facebook-clone-51212.firebasestorage.app',
    measurementId: 'G-F7MRCSZVCJ',
  );
}
